name: Bump patch version

on:
  pull_request:
    types: [closed]
    branches:
      - develop
jobs:
  call-workflow:
      uses: NitipatTh/github-action-shared-pipeline/.github/workflows/bump_patch_version.yaml@main
      with:
        ref: $GITHUB_REF
      secrets: inherit