name: Bump minor version

on:
  workflow_run:
    workflows: ["Deploy to beta"]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: refs/heads/develop

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: npm install
        run: npm install

      - name: npm bump prerelease no tag
        run: npm --no-git-tag-version version minor

      - name: Commit files
        run: |
          git config --local user.email "bot@nitipat.test"
          git config --local user.name "GitHub Action Bot"
          git add ./package-lock.json
          git add ./package.json
          git commit -m "[Bot] bump version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }} #ignore if your branch is master
          github_token: ${{ secrets.CICD_GITHUB_TOKEN }}
          force: true