name: Deploy to beta

on:
  pull_request:
    types: [closed]
    branches:
      - beta

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: NitipatTh/github-actions-test@v1
      with:
        who-to-greet: 'NitipatTh'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

  bump_minor_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Echo branch name
        run: |
          echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Checkout Code
        if: steps.branch-name.outputs.current_branch == 'develop'
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: refs/heads/develop

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.branch-name.outputs.current_branch == 'develop'
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: npm install
        if: steps.branch-name.outputs.current_branch == 'develop'
        run: npm install

      - name: npm bump prerelease no tag
        if: steps.branch-name.outputs.current_branch == 'develop'
        run: npm --no-git-tag-version version minor

      - name: Commit files
        if: steps.branch-name.outputs.current_branch == 'develop'
        run: |
          git config --local user.email "bot@nitipat.test"
          git config --local user.name "GitHub Action Bot"
          git add ./package-lock.json
          git add ./package.json
          git commit -m "[Bot] bump version"

      - name: Push changes
        if: steps.branch-name.outputs.current_branch == 'develop'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }} #ignore if your branch is master
          github_token: ${{ secrets.CICD_GITHUB_TOKEN }}
